// Generated by scripts/generate-embedded-db-types.mjs from applied migrations. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
assignments: { Row: {
id: string;
organization_id: string;
trip_id: string;
driver_id: string | null;
vehicle_id: string | null;
team_id: string | null;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
driver_id?: string | null;
vehicle_id?: string | null;
team_id?: string | null;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
driver_id?: string | null;
vehicle_id?: string | null;
team_id?: string | null;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
audit_logs: { Row: {
id: string;
organization_id: string | null;
actor_id: string | null;
action: string;
entity_type: string;
entity_id: string | null;
occurred_at: string;
metadata: Json;
before_data: Json | null;
after_data: Json | null;
}; Insert: {
id?: string;
organization_id?: string | null;
actor_id?: string | null;
action: string;
entity_type: string;
entity_id?: string | null;
occurred_at?: string;
metadata?: Json;
before_data?: Json | null;
after_data?: Json | null;
}; Update: {
id?: string;
organization_id?: string | null;
actor_id?: string | null;
action?: string;
entity_type?: string;
entity_id?: string | null;
occurred_at?: string;
metadata?: Json;
before_data?: Json | null;
after_data?: Json | null;
}; Relationships: [] };
branches: { Row: {
id: string;
organization_id: string;
name: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
name: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
name?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
customers: { Row: {
id: string;
organization_id: string;
profile_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
profile_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
profile_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
drivers: { Row: {
id: string;
organization_id: string;
profile_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
profile_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
profile_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
file_objects: { Row: {
id: string;
organization_id: string;
owner_profile_id: string;
bucket_id: string;
object_name: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
owner_profile_id: string;
bucket_id: string;
object_name?: never;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
owner_profile_id?: string;
bucket_id?: string;
object_name?: never;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
invoices: { Row: {
id: string;
organization_id: string;
order_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
issues: { Row: {
id: string;
organization_id: string;
request_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
jobs: { Row: {
id: string;
organization_id: string;
order_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
notification_templates: { Row: {
id: string;
organization_id: string;
template_key: string;
locale: string;
channel: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
template_key: string;
locale: string;
channel: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
template_key?: string;
locale?: string;
channel?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
notifications: { Row: {
id: string;
organization_id: string;
recipient_profile_id: string;
template_id: string | null;
idempotency_key: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
recipient_profile_id: string;
template_id?: string | null;
idempotency_key: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
recipient_profile_id?: string;
template_id?: string | null;
idempotency_key?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
orders: { Row: {
id: string;
organization_id: string;
quote_id: string;
accepted_quote_version_id: string;
idempotency_key: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
quote_id: string;
accepted_quote_version_id: string;
idempotency_key: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
quote_id?: string;
accepted_quote_version_id?: string;
idempotency_key?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
organization_memberships: { Row: {
organization_id: string;
profile_id: string;
branch_id: string | null;
member_type: string;
status: string;
created_at: string;
updated_at: string;
}; Insert: {
organization_id: string;
profile_id: string;
branch_id?: string | null;
member_type: string;
status?: string;
created_at?: string;
updated_at?: string;
}; Update: {
organization_id?: string;
profile_id?: string;
branch_id?: string | null;
member_type?: string;
status?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
organizations: { Row: {
id: string;
name: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
name: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
name?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
payment_transactions: { Row: {
id: string;
organization_id: string;
payment_id: string;
provider: string;
provider_event_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
payment_id: string;
provider: string;
provider_event_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
payment_id?: string;
provider?: string;
provider_event_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
payments: { Row: {
id: string;
organization_id: string;
order_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
permissions: { Row: {
id: string;
code: string;
}; Insert: {
id?: string;
code: string;
}; Update: {
id?: string;
code?: string;
}; Relationships: [] };
profiles: { Row: {
id: string;
display_name: string | null;
locale: string;
created_at: string;
updated_at: string;
}; Insert: {
id: string;
display_name?: string | null;
locale?: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
display_name?: string | null;
locale?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
quality_alerts: { Row: {
id: string;
organization_id: string;
trip_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
quote_items: { Row: {
id: string;
organization_id: string;
quote_version_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
quote_version_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
quote_version_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
quote_versions: { Row: {
id: string;
organization_id: string;
quote_id: string;
version: number;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
quote_id: string;
version: number;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
quote_id?: string;
version?: number;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
quotes: { Row: {
id: string;
organization_id: string;
request_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
request_attachments: { Row: {
id: string;
organization_id: string;
request_id: string;
file_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
file_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
file_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
request_items: { Row: {
id: string;
organization_id: string;
request_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
requests: { Row: {
id: string;
organization_id: string;
customer_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
customer_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
customer_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
reviews: { Row: {
id: string;
organization_id: string;
order_id: string;
customer_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
customer_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
customer_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
role_permissions: { Row: {
role_id: string;
permission_id: string;
}; Insert: {
role_id: string;
permission_id: string;
}; Update: {
role_id?: string;
permission_id?: string;
}; Relationships: [] };
roles: { Row: {
id: string;
code: string;
member_type: string;
}; Insert: {
id?: string;
code: string;
member_type: string;
}; Update: {
id?: string;
code?: string;
member_type?: string;
}; Relationships: [] };
service_areas: { Row: {
id: string;
organization_id: string;
service_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
service_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
service_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
services: { Row: {
id: string;
organization_id: string;
code: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
code: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
code?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
support_notes: { Row: {
id: string;
organization_id: string;
issue_id: string;
author_profile_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
issue_id: string;
author_profile_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
issue_id?: string;
author_profile_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
teams: { Row: {
id: string;
organization_id: string;
branch_id: string | null;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
trip_events: { Row: {
id: string;
organization_id: string;
trip_id: string;
stop_id: string | null;
event_type: string;
occurred_at: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
stop_id?: string | null;
event_type: string;
occurred_at?: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
stop_id?: string | null;
event_type?: string;
occurred_at?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
trip_stops: { Row: {
id: string;
organization_id: string;
trip_id: string;
position: number;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
position: number;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
position?: number;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
trips: { Row: {
id: string;
organization_id: string;
job_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
job_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
job_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
user_roles: { Row: {
organization_id: string;
profile_id: string;
role_id: string;
created_at: string;
}; Insert: {
organization_id: string;
profile_id: string;
role_id: string;
created_at?: string;
}; Update: {
organization_id?: string;
profile_id?: string;
role_id?: string;
created_at?: string;
}; Relationships: [] };
vehicles: { Row: {
id: string;
organization_id: string;
branch_id: string | null;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
}; Views: { [_ in never]: never }; Functions: { has_permission: { Args: { organization_id: string; permission_code: string }; Returns: boolean } }; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };
