// Generated by scripts/generate-embedded-db-types.mjs from applied migrations. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
additional_services: { Row: {
id: string;
organization_id: string;
code: string;
name_ar: string;
name_en: string;
active: boolean;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
code: string;
name_ar: string;
name_en: string;
active?: boolean;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
code?: string;
name_ar?: string;
name_en?: string;
active?: boolean;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"additional_services_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false}] };
assignments: { Row: {
id: string;
organization_id: string;
trip_id: string;
driver_id: string | null;
vehicle_id: string | null;
team_id: string | null;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
driver_id?: string | null;
vehicle_id?: string | null;
team_id?: string | null;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
driver_id?: string | null;
vehicle_id?: string | null;
team_id?: string | null;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"assignments_organization_id_driver_id_fkey","columns":["organization_id","driver_id"],"referencedRelation":"drivers","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"assignments_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"assignments_organization_id_team_id_fkey","columns":["organization_id","team_id"],"referencedRelation":"teams","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"assignments_organization_id_trip_id_fkey","columns":["organization_id","trip_id"],"referencedRelation":"trips","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"assignments_organization_id_vehicle_id_fkey","columns":["organization_id","vehicle_id"],"referencedRelation":"vehicles","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
audit_logs: { Row: {
id: string;
organization_id: string | null;
actor_id: string | null;
action: string;
entity_type: string;
entity_id: string | null;
occurred_at: string;
metadata: Json;
before_data: Json | null;
after_data: Json | null;
}; Insert: {
id?: string;
organization_id?: string | null;
actor_id?: string | null;
action: string;
entity_type: string;
entity_id?: string | null;
occurred_at?: string;
metadata?: Json;
before_data?: Json | null;
after_data?: Json | null;
}; Update: {
id?: string;
organization_id?: string | null;
actor_id?: string | null;
action?: string;
entity_type?: string;
entity_id?: string | null;
occurred_at?: string;
metadata?: Json;
before_data?: Json | null;
after_data?: Json | null;
}; Relationships: [{"foreignKeyName":"audit_logs_actor_id_fkey","columns":["actor_id"],"referencedRelation":"profiles","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"audit_logs_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false}] };
branches: { Row: {
id: string;
organization_id: string;
name: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
name: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
name?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"branches_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false}] };
customers: { Row: {
id: string;
organization_id: string;
profile_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
profile_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
profile_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"customers_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"customers_organization_id_profile_id_fkey","columns":["organization_id","profile_id"],"referencedRelation":"organization_memberships","referencedColumns":["organization_id","profile_id"],"isOneToOne":true}] };
drivers: { Row: {
id: string;
organization_id: string;
profile_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
profile_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
profile_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"drivers_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"drivers_organization_id_profile_id_fkey","columns":["organization_id","profile_id"],"referencedRelation":"organization_memberships","referencedColumns":["organization_id","profile_id"],"isOneToOne":true}] };
file_objects: { Row: {
id: string;
organization_id: string;
owner_profile_id: string;
bucket_id: string;
object_name: string;
created_at: string;
updated_at: string;
upload_state: string;
mime_type: string | null;
size_bytes: number | null;
}; Insert: {
id?: string;
organization_id: string;
owner_profile_id: string;
bucket_id: string;
object_name?: never;
created_at?: string;
updated_at?: string;
upload_state?: string;
mime_type?: string | null;
size_bytes?: number | null;
}; Update: {
id?: string;
organization_id?: string;
owner_profile_id?: string;
bucket_id?: string;
object_name?: never;
created_at?: string;
updated_at?: string;
upload_state?: string;
mime_type?: string | null;
size_bytes?: number | null;
}; Relationships: [{"foreignKeyName":"file_objects_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"file_objects_organization_id_owner_profile_id_fkey","columns":["organization_id","owner_profile_id"],"referencedRelation":"organization_memberships","referencedColumns":["organization_id","profile_id"],"isOneToOne":false}] };
invoices: { Row: {
id: string;
organization_id: string;
order_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"invoices_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"invoices_organization_id_order_id_fkey","columns":["organization_id","order_id"],"referencedRelation":"orders","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
issues: { Row: {
id: string;
organization_id: string;
request_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"issues_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"issues_organization_id_request_id_fkey","columns":["organization_id","request_id"],"referencedRelation":"requests","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
jobs: { Row: {
id: string;
organization_id: string;
order_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"jobs_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"jobs_organization_id_order_id_fkey","columns":["organization_id","order_id"],"referencedRelation":"orders","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
notification_templates: { Row: {
id: string;
organization_id: string;
template_key: string;
locale: string;
channel: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
template_key: string;
locale: string;
channel: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
template_key?: string;
locale?: string;
channel?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"notification_templates_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false}] };
notifications: { Row: {
id: string;
organization_id: string;
recipient_profile_id: string;
template_id: string | null;
idempotency_key: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
recipient_profile_id: string;
template_id?: string | null;
idempotency_key: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
recipient_profile_id?: string;
template_id?: string | null;
idempotency_key?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"notifications_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"notifications_organization_id_recipient_profile_id_fkey","columns":["organization_id","recipient_profile_id"],"referencedRelation":"organization_memberships","referencedColumns":["organization_id","profile_id"],"isOneToOne":false},{"foreignKeyName":"notifications_organization_id_template_id_fkey","columns":["organization_id","template_id"],"referencedRelation":"notification_templates","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
orders: { Row: {
id: string;
organization_id: string;
quote_id: string;
accepted_quote_version_id: string;
idempotency_key: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
quote_id: string;
accepted_quote_version_id: string;
idempotency_key: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
quote_id?: string;
accepted_quote_version_id?: string;
idempotency_key?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"orders_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"orders_organization_id_quote_id_accepted_quote_version_id_fkey","columns":["organization_id","quote_id","accepted_quote_version_id"],"referencedRelation":"quote_versions","referencedColumns":["organization_id","quote_id","id"],"isOneToOne":false}] };
organization_memberships: { Row: {
organization_id: string;
profile_id: string;
branch_id: string | null;
member_type: string;
status: string;
created_at: string;
updated_at: string;
}; Insert: {
organization_id: string;
profile_id: string;
branch_id?: string | null;
member_type: string;
status?: string;
created_at?: string;
updated_at?: string;
}; Update: {
organization_id?: string;
profile_id?: string;
branch_id?: string | null;
member_type?: string;
status?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"organization_memberships_organization_id_branch_id_fkey","columns":["organization_id","branch_id"],"referencedRelation":"branches","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"organization_memberships_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"organization_memberships_profile_id_fkey","columns":["profile_id"],"referencedRelation":"profiles","referencedColumns":["id"],"isOneToOne":false}] };
organizations: { Row: {
id: string;
name: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
name: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
name?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [] };
payment_transactions: { Row: {
id: string;
organization_id: string;
payment_id: string;
provider: string;
provider_event_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
payment_id: string;
provider: string;
provider_event_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
payment_id?: string;
provider?: string;
provider_event_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"payment_transactions_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"payment_transactions_organization_id_payment_id_fkey","columns":["organization_id","payment_id"],"referencedRelation":"payments","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
payments: { Row: {
id: string;
organization_id: string;
order_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"payments_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"payments_organization_id_order_id_fkey","columns":["organization_id","order_id"],"referencedRelation":"orders","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
permissions: { Row: {
id: string;
code: string;
}; Insert: {
id?: string;
code: string;
}; Update: {
id?: string;
code?: string;
}; Relationships: [] };
profiles: { Row: {
id: string;
display_name: string | null;
locale: string;
created_at: string;
updated_at: string;
phone: string | null;
}; Insert: {
id: string;
display_name?: string | null;
locale?: string;
created_at?: string;
updated_at?: string;
phone?: string | null;
}; Update: {
id?: string;
display_name?: string | null;
locale?: string;
created_at?: string;
updated_at?: string;
phone?: string | null;
}; Relationships: [{"foreignKeyName":"profiles_id_fkey","columns":["id"],"referencedRelation":"users","referencedColumns":["id"],"isOneToOne":true}] };
quality_alerts: { Row: {
id: string;
organization_id: string;
trip_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"quality_alerts_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"quality_alerts_organization_id_trip_id_fkey","columns":["organization_id","trip_id"],"referencedRelation":"trips","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
quote_items: { Row: {
id: string;
organization_id: string;
quote_version_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
quote_version_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
quote_version_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"quote_items_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"quote_items_organization_id_quote_version_id_fkey","columns":["organization_id","quote_version_id"],"referencedRelation":"quote_versions","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
quote_versions: { Row: {
id: string;
organization_id: string;
quote_id: string;
version: number;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
quote_id: string;
version: number;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
quote_id?: string;
version?: number;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"quote_versions_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"quote_versions_organization_id_quote_id_fkey","columns":["organization_id","quote_id"],"referencedRelation":"quotes","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
quotes: { Row: {
id: string;
organization_id: string;
request_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"quotes_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"quotes_organization_id_request_id_fkey","columns":["organization_id","request_id"],"referencedRelation":"requests","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
request_additional_services: { Row: {
request_id: string;
organization_id: string;
additional_service_id: string;
}; Insert: {
request_id: string;
organization_id: string;
additional_service_id: string;
}; Update: {
request_id?: string;
organization_id?: string;
additional_service_id?: string;
}; Relationships: [{"foreignKeyName":"request_additional_services_organization_id_additional_ser_fkey","columns":["organization_id","additional_service_id"],"referencedRelation":"additional_services","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"request_additional_services_organization_id_request_id_fkey","columns":["organization_id","request_id"],"referencedRelation":"requests","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
request_attachments: { Row: {
id: string;
organization_id: string;
request_id: string;
file_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
file_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
file_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"request_attachments_organization_id_file_id_fkey","columns":["organization_id","file_id"],"referencedRelation":"file_objects","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"request_attachments_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"request_attachments_organization_id_request_id_fkey","columns":["organization_id","request_id"],"referencedRelation":"requests","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
request_items: { Row: {
id: string;
organization_id: string;
request_id: string;
created_at: string;
updated_at: string;
description: string;
quantity: number;
notes: string;
position: number;
}; Insert: {
id?: string;
organization_id: string;
request_id: string;
created_at?: string;
updated_at?: string;
description?: string;
quantity?: number;
notes?: string;
position?: number;
}; Update: {
id?: string;
organization_id?: string;
request_id?: string;
created_at?: string;
updated_at?: string;
description?: string;
quantity?: number;
notes?: string;
position?: number;
}; Relationships: [{"foreignKeyName":"request_items_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"request_items_organization_id_request_id_fkey","columns":["organization_id","request_id"],"referencedRelation":"requests","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
request_locations: { Row: {
request_id: string;
organization_id: string;
kind: string;
city: string;
district: string;
address: string;
notes: string;
floor: number | null;
elevator: boolean | null;
access_notes: string;
}; Insert: {
request_id: string;
organization_id: string;
kind: string;
city?: string;
district?: string;
address?: string;
notes?: string;
floor?: number | null;
elevator?: boolean | null;
access_notes?: string;
}; Update: {
request_id?: string;
organization_id?: string;
kind?: string;
city?: string;
district?: string;
address?: string;
notes?: string;
floor?: number | null;
elevator?: boolean | null;
access_notes?: string;
}; Relationships: [{"foreignKeyName":"request_locations_organization_id_request_id_fkey","columns":["organization_id","request_id"],"referencedRelation":"requests","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
requests: { Row: {
id: string;
organization_id: string;
customer_id: string;
created_at: string;
updated_at: string;
status: string;
revision: number;
creation_key: string | null;
last_mutation_id: string | null;
service_id: string | null;
description: string;
notes: string;
preferred_date: string | null;
time_window: string | null;
contact_name: string;
contact_phone: string;
contact_email: string;
contact_notes: string;
reference: string | null;
submitted_at: string | null;
}; Insert: {
id?: string;
organization_id: string;
customer_id: string;
created_at?: string;
updated_at?: string;
status?: string;
revision?: number;
creation_key?: string | null;
last_mutation_id?: string | null;
service_id?: string | null;
description?: string;
notes?: string;
preferred_date?: string | null;
time_window?: string | null;
contact_name?: string;
contact_phone?: string;
contact_email?: string;
contact_notes?: string;
reference?: string | null;
submitted_at?: string | null;
}; Update: {
id?: string;
organization_id?: string;
customer_id?: string;
created_at?: string;
updated_at?: string;
status?: string;
revision?: number;
creation_key?: string | null;
last_mutation_id?: string | null;
service_id?: string | null;
description?: string;
notes?: string;
preferred_date?: string | null;
time_window?: string | null;
contact_name?: string;
contact_phone?: string;
contact_email?: string;
contact_notes?: string;
reference?: string | null;
submitted_at?: string | null;
}; Relationships: [{"foreignKeyName":"requests_organization_id_customer_id_fkey","columns":["organization_id","customer_id"],"referencedRelation":"customers","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"requests_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"requests_service_fk","columns":["organization_id","service_id"],"referencedRelation":"services","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
reviews: { Row: {
id: string;
organization_id: string;
order_id: string;
customer_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
order_id: string;
customer_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
order_id?: string;
customer_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"reviews_organization_id_customer_id_fkey","columns":["organization_id","customer_id"],"referencedRelation":"customers","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"reviews_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"reviews_organization_id_order_id_fkey","columns":["organization_id","order_id"],"referencedRelation":"orders","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
role_permissions: { Row: {
role_id: string;
permission_id: string;
}; Insert: {
role_id: string;
permission_id: string;
}; Update: {
role_id?: string;
permission_id?: string;
}; Relationships: [{"foreignKeyName":"role_permissions_permission_id_fkey","columns":["permission_id"],"referencedRelation":"permissions","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"role_permissions_role_id_fkey","columns":["role_id"],"referencedRelation":"roles","referencedColumns":["id"],"isOneToOne":false}] };
roles: { Row: {
id: string;
code: string;
member_type: string;
}; Insert: {
id?: string;
code: string;
member_type: string;
}; Update: {
id?: string;
code?: string;
member_type?: string;
}; Relationships: [] };
service_areas: { Row: {
id: string;
organization_id: string;
service_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
service_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
service_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"service_areas_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"service_areas_organization_id_service_id_fkey","columns":["organization_id","service_id"],"referencedRelation":"services","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
services: { Row: {
id: string;
organization_id: string;
code: string;
created_at: string;
updated_at: string;
name_ar: string | null;
name_en: string | null;
active: boolean;
property_required: boolean;
}; Insert: {
id?: string;
organization_id: string;
code: string;
created_at?: string;
updated_at?: string;
name_ar?: string | null;
name_en?: string | null;
active?: boolean;
property_required?: boolean;
}; Update: {
id?: string;
organization_id?: string;
code?: string;
created_at?: string;
updated_at?: string;
name_ar?: string | null;
name_en?: string | null;
active?: boolean;
property_required?: boolean;
}; Relationships: [{"foreignKeyName":"services_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false}] };
support_notes: { Row: {
id: string;
organization_id: string;
issue_id: string;
author_profile_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
issue_id: string;
author_profile_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
issue_id?: string;
author_profile_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"support_notes_organization_id_author_profile_id_fkey","columns":["organization_id","author_profile_id"],"referencedRelation":"organization_memberships","referencedColumns":["organization_id","profile_id"],"isOneToOne":false},{"foreignKeyName":"support_notes_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"support_notes_organization_id_issue_id_fkey","columns":["organization_id","issue_id"],"referencedRelation":"issues","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
teams: { Row: {
id: string;
organization_id: string;
branch_id: string | null;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"teams_organization_id_branch_id_fkey","columns":["organization_id","branch_id"],"referencedRelation":"branches","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"teams_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false}] };
trip_events: { Row: {
id: string;
organization_id: string;
trip_id: string;
stop_id: string | null;
event_type: string;
occurred_at: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
stop_id?: string | null;
event_type: string;
occurred_at?: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
stop_id?: string | null;
event_type?: string;
occurred_at?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"trip_events_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"trip_events_organization_id_trip_id_fkey","columns":["organization_id","trip_id"],"referencedRelation":"trips","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"trip_events_stop_fk","columns":["organization_id","trip_id","stop_id"],"referencedRelation":"trip_stops","referencedColumns":["organization_id","trip_id","id"],"isOneToOne":false}] };
trip_stops: { Row: {
id: string;
organization_id: string;
trip_id: string;
position: number;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
trip_id: string;
position: number;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
trip_id?: string;
position?: number;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"trip_stops_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"trip_stops_organization_id_trip_id_fkey","columns":["organization_id","trip_id"],"referencedRelation":"trips","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
trips: { Row: {
id: string;
organization_id: string;
job_id: string;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
job_id: string;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
job_id?: string;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"trips_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false},{"foreignKeyName":"trips_organization_id_job_id_fkey","columns":["organization_id","job_id"],"referencedRelation":"jobs","referencedColumns":["organization_id","id"],"isOneToOne":false}] };
user_roles: { Row: {
organization_id: string;
profile_id: string;
role_id: string;
created_at: string;
}; Insert: {
organization_id: string;
profile_id: string;
role_id: string;
created_at?: string;
}; Update: {
organization_id?: string;
profile_id?: string;
role_id?: string;
created_at?: string;
}; Relationships: [{"foreignKeyName":"user_roles_organization_id_profile_id_fkey","columns":["organization_id","profile_id"],"referencedRelation":"organization_memberships","referencedColumns":["organization_id","profile_id"],"isOneToOne":false},{"foreignKeyName":"user_roles_role_id_fkey","columns":["role_id"],"referencedRelation":"roles","referencedColumns":["id"],"isOneToOne":false}] };
vehicles: { Row: {
id: string;
organization_id: string;
branch_id: string | null;
created_at: string;
updated_at: string;
}; Insert: {
id?: string;
organization_id: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Update: {
id?: string;
organization_id?: string;
branch_id?: string | null;
created_at?: string;
updated_at?: string;
}; Relationships: [{"foreignKeyName":"vehicles_organization_id_branch_id_fkey","columns":["organization_id","branch_id"],"referencedRelation":"branches","referencedColumns":["organization_id","id"],"isOneToOne":false},{"foreignKeyName":"vehicles_organization_id_fkey","columns":["organization_id"],"referencedRelation":"organizations","referencedColumns":["id"],"isOneToOne":false}] };
}; Views: { [_ in never]: never }; Functions: { create_customer_request: { Args: { p_key: string }; Returns: Json };customer_enrollment_state: { Args: { [_ in never]: never }; Returns: string };has_permission: { Args: { organization_id: string; permission_code: string }; Returns: boolean };onboard_customer: { Args: { p_name: string; p_phone: string; p_locale: string }; Returns: string };request_command: { Args: { p_operation: string; p_request_id: string; p_revision: number; p_mutation_id: string; p_payload?: Json }; Returns: Json };request_file_command: { Args: { p_operation: string; p_request_id: string; p_file_id: string; p_mime?: string; p_size?: number }; Returns: Json } }; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };
